name: "Terraform Apply (Manual)"

on:
  workflow_dispatch:
    inputs:
      deploy_app:
        description: 'Check this to trigger App Deployment after Apply'
        required: true
        type: boolean
        default: false

permissions:
  id-token: write
  contents: read

jobs:
  terraform-apply:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: "${{ vars.AWS_REGION }}"

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::${{ vars.AWS_ACCOUNT_ID }}:role/GitHubActionsWorkflowRole
          role-session-name: github-actions-session
          aws-region: ${{ vars.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3.1.2

      - name: Generate SSH Key Files from Secrets
        run: |
          mkdir -p files
          echo "${{ secrets.SSH_PUBLIC_KEY }}" > ./files/s3-app-key.pub

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve

      - name: Trigger App Repo Deployment
        # This only runs if you checked the box when clicking "Run Workflow"
        if: github.event.inputs.deploy_app == 'true'
        env:
          GH_TOKEN: ${{ secrets.S3_APP_CODE_REPO_ACCESS }} # Personal access token
        run: |
          gh workflow run deploy.yml \
            --repo ${{ vars.CODE_REPO_USERNAME }}/${{ vars.CODE_REPO }} \
            --ref main
